// examples/ui/react/parts-list/App.tsx
import type { PartsDomain } from '../../../apps/parts-list/parts-domain'
import { ManufacturerView } from './ManufacturerView'

export function App({ domain }: { domain: PartsDomain }) {
  const entities = domain.entities.entities
  const allParts = domain.allParts.items
  const allSorting = domain.allParts.sorting.state
  const manufacturerKeys = domain.manufacturerViews.keys
  const manufacturerViews = domain.manufacturerViews.items
  return (
    <div className="parts-page">
      <div className="toolbar">
        <span>{entities.value.size} normalized entities</span>
        <button type="button" onClick={domain.addPart}>Add Northwind part</button>
      </div>

      <section className="panel">
        <div className="panel-heading">
          <div><h2>All parts</h2><small>Sorted by {allSorting.value.field} · {allSorting.value.direction}</small></div>
          <button type="button" onClick={domain.toggleAllSort}>Toggle sort</button>
        </div>
        <table>
          <thead><tr><th>Part</th><th>Manufacturer</th><th>Price</th><th>Stock</th><th>Actions</th></tr></thead>
          <tbody>
            {allParts.value.map((part) => (
              <tr key={part.id}>
                <td>{part.name}</td><td>{part.manufacturer}</td><td>${part.price.toFixed(2)}</td><td>{part.stock}</td>
                <td className="actions">
                  <button type="button" onClick={() => domain.increasePrice(part.id)}>+$1</button>
                  <button className="danger" type="button" onClick={() => domain.deletePart(part.id)}>Delete</button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </section>

      <div className="toolbar view-toolbar">
        <span>Manufacturer views</span>
        <div className="actions">
          {domain.manufacturers
            .filter((manufacturer) => !manufacturerKeys.value.includes(manufacturer))
            .map((manufacturer) => (
              <button
                key={manufacturer}
                type="button"
                onClick={() => domain.createManufacturerView(manufacturer)}
              >
                Add {manufacturer}
              </button>
            ))}
        </div>
      </div>

      {manufacturerViews.value.map((view) => (
        <ManufacturerView key={view.id} domain={domain} view={view} />
      ))}
    </div>
  )
}

// examples/apps/parts-list/App.vue
<script setup lang="ts">
import type { PartsDomain } from './parts-domain'

const props = defineProps<{ domain: PartsDomain }>()
const entities = props.domain.entities.entities
const allParts = props.domain.allParts.items
const allSorting = props.domain.allParts.sorting.state
const manufacturerKeys = props.domain.manufacturerViews.keys
const manufacturerViews = props.domain.manufacturerViews.items
</script>

<template>
  <div class="parts-page">
    <div class="toolbar">
      <span>{{ entities.size }} normalized entities</span>
      <button type="button" @click="domain.addPart">Add Northwind part</button>
    </div>

    <section class="panel">
      <div class="panel-heading">
        <div><h2>All parts</h2><small>Sorted by {{ allSorting.field }} · {{ allSorting.direction }}</small></div>
        <button type="button" @click="domain.toggleAllSort">Toggle sort</button>
      </div>
      <table>
        <thead><tr><th>Part</th><th>Manufacturer</th><th>Price</th><th>Stock</th><th>Actions</th></tr></thead>
        <tbody>
          <tr v-for="part in allParts" :key="part.id">
            <td>{{ part.name }}</td><td>{{ part.manufacturer }}</td><td>${{ part.price.toFixed(2) }}</td><td>{{ part.stock }}</td>
            <td class="actions"><button type="button" @click="domain.increasePrice(part.id)">+$1</button><button class="danger" type="button" @click="domain.deletePart(part.id)">Delete</button></td>
          </tr>
        </tbody>
      </table>
    </section>

    <div class="toolbar view-toolbar">
      <span>Manufacturer views</span>
      <div class="actions">
        <button
          v-for="manufacturer in domain.manufacturers.filter((name) => !manufacturerKeys.includes(name))"
          :key="manufacturer"
          type="button"
          @click="domain.createManufacturerView(manufacturer)"
        >Add {{ manufacturer }}</button>
      </div>
    </div>

    <section v-for="view in manufacturerViews" :key="view.id" class="panel">
      <div class="panel-heading">
        <div>
          <h2>{{ view.filtering.state.get().manufacturer }} view</h2>
          <small>Price {{ view.sorting.state.get().direction }}</small>
        </div>
        <button class="danger" type="button" @click="domain.deleteManufacturerView(view.filtering.state.get().manufacturer)">Remove view</button>
      </div>
      <table>
        <thead><tr><th>Part</th><th>Price</th><th>Stock</th></tr></thead>
        <tbody>
          <tr v-for="part in view.items.get()" :key="part.id">
            <td>{{ part.name }}</td><td>${{ part.price.toFixed(2) }}</td><td>{{ part.stock }}</td>
          </tr>
        </tbody>
      </table>
    </section>
  </div>
</template>

<style src="./style.css" scoped></style>
