// examples/ui/svelte/counter/App.svelte
<script lang="ts">
  import type { CounterController } from '../../../apps/counter/domain'

  let { controller }: { controller: CounterController } = $props()
  const count = controller.count
</script>

<section class="counter-card">
  <div class="counter-value">{count.value}</div>
  <div class="counter-actions">
    <button type="button" onclick={controller.decrement}>−</button>
    <button type="button" onclick={controller.reset}>Reset</button>
    <button type="button" onclick={controller.increment}>+</button>
  </div>
</section>

// examples/ui/react/counter/App.tsx
import type { CounterController } from '../../../apps/counter/domain'

export function App({ controller }: { controller: CounterController }) {
  const count = controller.count
  return (
    <section className="counter-card">
      <div className="counter-value">{count.value}</div>
      <div className="counter-actions">
        <button type="button" onClick={controller.decrement}>−</button>
        <button type="button" onClick={controller.reset}>Reset</button>
        <button type="button" onClick={controller.increment}>+</button>
      </div>
    </section>
  )
}
